name: stacked_starter
description: Starter pack for flutter using stacked architecture

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  stacked: ^1.7.6
  auto_route: ^0.6.7
  get_it: ^4.0.4
  injectable: ^1.0.4
  stacked_services: ^0.5.4
  stacked_hooks: ^0.1.3
  flutter_hooks: ^0.12.0
  observable_ish:
  json_annotation: ^3.0.1
  dio: ^3.0.10
  flutter_secure_storage: ^3.3.3
  provider: ^4.3.2
  flutter_dotenv: ^2.1.0
  async: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4
  json_serializable: ^3.3.0

flutter:
  assets:
    - assets/env/.env_dev
    - assets/env/.env_prod
  uses-material-design: true